const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Behaviors.MoveTo,
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.EightDir.Cnds.IsEnabled,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SetPos,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Keyboard.Cnds.OnKey
	];
};
self.C3_JsPropNameTable = [
	{Shild: 0},
	{Trap: 0},
	{GetKey: 0},
	{GetMana: 0},
	{ManaActive: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{Hero: 0},
	{Sine: 0},
	{Minos: 0},
	{TiledBackground: 0},
	{Solid: 0},
	{Wall: 0},
	{Chest_close: 0},
	{Chest_open_: 0},
	{button_replay: 0},
	{Mouse: 0},
	{Trap_collectible: 0},
	{ManaPotion: 0},
	{Door_close: 0},
	{Door_open_: 0},
	{text_total_timer: 0},
	{Text: 0},
	{Text2: 0},
	{Text3: 0},
	{Text4: 0},
	{Chest_trap: 0},
	{bad_trap: 0},
	{Mimic: 0},
	{key: 0},
	{KeySpawner: 0},
	{Key_UI: 0},
	{MoveTo: 0},
	{InTheHell: 0},
	{Keyboard: 0},
	{Door_tuto: 0},
	{door_open_tuto: 0},
	{tuto_key: 0},
	{Text5: 0},
	{Text6: 0},
	{Text7: 0},
	{ManaPotion_UI: 0},
	{WallSecret: 0},
	{timer: 0}
];

self.InstanceType = {
	Hero: class extends self.ISpriteInstance {},
	Minos: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Wall: class extends self.ISpriteInstance {},
	Chest_close: class extends self.ISpriteInstance {},
	Chest_open_: class extends self.ISpriteInstance {},
	button_replay: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Trap: class extends self.ISpriteInstance {},
	Trap_collectible: class extends self.ISpriteInstance {},
	ManaPotion: class extends self.ISpriteInstance {},
	Door_close: class extends self.ISpriteInstance {},
	Door_open_: class extends self.ISpriteInstance {},
	text_total_timer: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	Chest_trap: class extends self.ISpriteInstance {},
	bad_trap: class extends self.ISpriteInstance {},
	Mimic: class extends self.ISpriteInstance {},
	key: class extends self.ISpriteInstance {},
	KeySpawner: class extends self.ISpriteInstance {},
	Key_UI: class extends self.ISpriteInstance {},
	InTheHell: class extends self.ITextInstance {},
	Keyboard: class extends self.IInstance {},
	Door_tuto: class extends self.ISpriteInstance {},
	door_open_tuto: class extends self.ISpriteInstance {},
	tuto_key: class extends self.ISpriteInstance {},
	Text5: class extends self.ITextInstance {},
	Text6: class extends self.ITextInstance {},
	Text7: class extends self.ITextInstance {},
	ManaPotion_UI: class extends self.ISpriteInstance {},
	WallSecret: class extends self.ISpriteInstance {}
}